#!/usr/bin/env bash
set -euo pipefail

if ! command -v cc >/dev/null; then
  sudo apt-get update
  sudo apt-get install -y build-essential
fi
if [[ ! -x "$HOME/.cargo/bin/rustup" ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
fi
source "$HOME/.cargo/env"
rustup component add rustfmt clippy
cargo fetch --locked
